SELECT escuela;

CREATE FUNCTION SUMAR(@NUM1 INT, @NUM2 INT)
RETURNS INT
AS
BEGIN
    DECLARE @RESULTADO INT;
    DECLARE @N1 INT, @N2 INT;
    
    SET @N1 = @NUM1;
    SET @N2 = @NUM2;

    SET @RESULTADO = @N1 + @N2;
    RETURN @RESULTADO;
END